### ISSUE TITLE
Add Template for Pull Request

### ISSUE THREAD

**Issue by jimenezz22** [ByteBuildersLabs/Website#24]
The template must have the following parts:
- Title: Pull Request Overview
- Summary
- Changes Made
- Tests Results
- Next Steps

Use the following photo as an example:
<img width="833" alt="Screenshot 2024-10-29 at 11 36 24 AM" src="https://github.com/user-attachments/assets/b6c875ea-380d-4be9-9291-9ca3969b20ed">

**Comment by martinvibes** [comment]
I'd love to work on this!
Kindly assign

**Comment by mayasimi** [comment]
Could I be assigned to this issue? 

I am new  to the onlydust platform and would like to make this my first contribution to this platform and open source contribution .

kindly assign. Am experienced in Js and typescript

**Comment by CollinsC1O** [comment]
I'd be happy to do this.

**Comment by DiegoB1911** [comment]
I'm a Full Stack Developer with two years of experience. I'm also a member of Dojo Coding, where I'm expanding my expertise in Cairo and Web3 technologies. I'm enthusiastic about learning, and becoming a part of this project.
To address this issue, I would take the following steps:

1. Create the Template File:  
   I would create a new file named pull_request_template.md.

2. Define the Structure of the Template:  
   I will adjust the pull_request_template.md file to include the required sections.

3. Test the Template:  
 I would ensure that the template works by creating a new pull request in the repository and verifying that it automatically populates the description area, allowing contributors to fill in the necessary details.

**Comment by MPSxDev** [comment]
I would love to take on this issue. I am a member of the Dojo Coding. I am immediately available. @jimenezz22

**Comment by derianrddev** [comment]
Hello, I’m Derian, a software engineer focused on full-stack web development, and I’m currently part of Dojo Coding. I’d like to work on this issue.

Here’s how I would solve the issue:

Create the .github folder in the root of the repository.
Add the template within that folder with the parts described in the issue.
Save and upload the file to the repository.
If I have any questions, I’ll ask in the Telegram group as soon as possible.
I’ll open a PR and wait for your feedback.
I’ll make the necessary changes according to the PR review.

**Comment by JosueBrenes** [comment]
Hi, I'm **Josué Brenes** and I'll be working on issue.
I'm Dojo Coding member.

I estimate this will take **1 day** to complete.

To resolve this, I would create a Markdown template file (pull_request_template.md) in the .github directory of the repository. This file would include the required sections in Markdown format, making it automatically available in each Pull Request.

```tsx

# Pull Request Overview

## 📝 Summary
- Closes #(issue)
- Brief description of the purpose of the Pull Request.

## 🔄 Changes Made
- List of code changes, specifying the modules or sections affected.

## 🧪 Tests Results
- Results of the tests executed.
  - Example: "Unit tests: 15/15 passed"
  - Example: "Integration tests: 10/10 passed"

## 🚀 Next Steps
- Pending actions or next steps if applicable (e.g., additional reviews or tests by other teams).
```

**Comment by akintewe** [comment]
Hello, i would love if i can be assigned this issue, this is my first too, I’d like to help with this. I am very familiar with the documentation architecture, and i would love to be given the opportunity to work on this. Thank you so much. ETA <6 hrs

**Comment by sigmadawg** [comment]
im a newbie contributor, i'd be grateful if you'd give me the opportunity to work in this.

**Comment by jimenezz22** [comment]
assigned to you @JosueBrenes
